### PR TITLE
docs: Add ANAVI Macro Pad 10

### PR DESCRIPTION
**Pull request by leon-anavi**
Add ANAVI Macro Pad 10. Mini hot-swappable mechanical keyboard with a clickable rotary encoder, 9 Gateron switches, translucent keycaps, USB-C, RP2040 microcontroller, backlighting and under lighting.

### CODE REVIEW

**Comment by aatmmr** [comment]
@leon-anavi Thank your contribution. Sorry for being 🐢 slow on the response. There are apparently some merge. Are you willing to resolve those to get the PR back on track?

**Comment by leon-anavi** [comment]
> @leon-anavi Thank your contribution. Sorry for being 🐢 slow on the response. There are apparently some merge. Are you willing to resolve those to get the PR back on track?

Yes, sure. I will have a look and update the PR in the coming days.

**Comment by leon-anavi** [comment]
@aatmmr, @BenRoe I've updated the GitHub pull request. Please have a look and let me know if any additional changes are required.

**Comment by leon-anavi** [comment]
> @leon-anavi feel free to merge it 😃

I don't have push access to this repository therefore I cannot merge it. Did you tag me by mistake instead of @BenRoe ?

**Pull request merged**
